export const HockeyTeams: string[] = [
    'Canadiens',
    'Avalanche',
    'Blackhawks',
    'Blues',
    'Blue Jackets',
    'Bruins',
    'Canucks',
    'Capitals',
    'Coyotes',
    'Devils',
    'Ducks',
    'Flames',
    'Flyers',
    'Golden Knights',
    'Hurricanes',
    'Islanders',
    'Jets',
    'Kings',
    'Kraken',
    'Maple Leafs',
    'Lightning',
    'Oilers',
    'Panthers',
    'Penguins',
    'Predators',
    'Rangers',
    'Red Wings',
    'Sabres',
    'Senators',
    'Sharks',
    'Stars',
    'Wild'
];
